services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: alati
      POSTGRES_PASSWORD: alati
      POSTGRES_DB: alati
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alati -d alati"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build: ../backend
    environment:
      DATABASE_URL: postgresql+psycopg://alati:alati@postgres:5432/alati
      REDIS_URL: redis://redis:6379/0
      JWT_SECRET: "CHANGE_ME_NOW"
      STORAGE_MODE: "local"
      LOCAL_STORAGE_DIR: "/data"
      MODEL_VARIANT: "resnet18"
      TRIAGE_THRESHOLD: "0.6"
    ports:
      - "8000:8000"
    volumes:
      - localdata:/data
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  worker:
    build: ../worker
    environment:
      DATABASE_URL: postgresql+psycopg://alati:alati@postgres:5432/alati
      REDIS_URL: redis://redis:6379/0
      JWT_SECRET: "CHANGE_ME_NOW"
      STORAGE_MODE: "local"
      LOCAL_STORAGE_DIR: "/data"
      MODEL_VARIANT: "resnet18"
      TRIAGE_THRESHOLD: "0.6"
    volumes:
      - localdata:/data
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  localdata:

